### ISSUE TITLE
不支持Odyssey越狱

### ISSUE THREAD

**Issue by ikanam** [creantan/LookinLoader#10]
Odyssey更新了PreferenceLoader后，Lookin的设置页面会报错，无法选择App。

**Comment by lexrus** [comment]
+1，点 Enabled Applications 直接 crash 了。

**Comment by 0x1306a94** [comment]
添加 `https://rpetri.ch/repo` 源, 然后更新`RocketBootstrap`

**Comment by lexrus** [comment]
试了一下，可以了，感谢 @0x1306a94

**Comment by songxing10000** [comment]
我是降到1.0.7就好使了

**Comment by League2EB** [comment]
> +1，点 Enabled Applications 直接 crash 了。

@creantan 相当依赖该工具进行开发与调适，想询问是否可能协助修复🙇‍♂️
谢谢您的努力

使用了 [palera1n](https://github.com/palera1n/palera1n)进行越狱后
即使安装了[rpetri源](https://rpetri.ch/repo), 然后更新RocketBootstrap，一样会闪退
系统条件如下
- iOS 15.1
- iPhone 6s
