### ISSUE TITLE
Can't trace daemons UI and another processes. Please add an option to load into any process.

### ISSUE THREAD

**Issue by ghost** [creantan/LookinLoader#15]

**Comment by creantan** [comment]
frida script
`
let lookinLoaderPath = "/usr/lib/Lookin/LookinServer.framework/LookinServer"

let lkModule =  Module.load(lookinLoaderPath)
console.log('[+]module name:',lkModule.name)
console.log('[+]module path:',lkModule.path)
console.log('[+]module base:',lkModule.base)
`

frida -U -l a.js -p PID
