### ISSUE TITLE
iOS 15.6 打开LookinLoader选择Enable Applications闪退

### ISSUE THREAD

**Issue by hsuyelin** [creantan/LookinLoader#18]
系统版本：iOS 15.6
设备：iPhone X
越狱工具：Palera1n
越狱商店：Sileo

**Comment by creantan** [comment]
应该是PreferenceLoader的问题，可以试试frida https://github.com/creantan/LookinLoader#frida-script-load-into-any-process

**Comment by hsuyelin** [comment]
@creantan 

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/17918063/206332779-4f94ddc0-c2b9-4f93-a45e-eaac6131c973.png">

加载成功了，比如说像系统app "Watch" 图层显示都是CALayer ，大佬，是需要额外设置什么才可以展示实际的么

**Comment by creantan** [comment]
@hsuyelin 你可以去Lookin咨询下

**Comment by areslk** [comment]
这个问题后面会修吗？

**Comment by 0x1306a94** [comment]
> @creantan
> 
> <img alt="image" width="1339" src="https://user-images.githubusercontent.com/17918063/206332779-4f94ddc0-c2b9-4f93-a45e-eaac6131c973.png">
> 
> 加载成功了，比如说像系统app "Watch" 图层显示都是CALayer ，大佬，是需要额外设置什么才可以展示实际的么

https://github.com/QMUI/LookinServer/pull/133 参考这里，自己编译个LookinServer.framework
