### ISSUE TITLE
怎麽有效果?

### ISSUE THREAD

**Issue by League2EB** [creantan/LookinLoader#2]
您好，我在Cydia上发现了您这套软件
以下是我的步骤
1.安装
2.开启设定中的LookinLoader
3.将我想要查看的APP加入
4.开启想查看的应用并且摇晃

有出现选单，但是点击之后没有任何事情发生?
我是不是少做了甚麽事情呢?

**Comment by creantan** [comment]
可以安装1.0.4版本的试下：https://github.com/creantan/LookinLoader/releases
或者等Cydia上更新

**Comment by League2EB** [comment]
> 可以安装1.0.4版本的试下：https://github.com/creantan/LookinLoader/releases
> 或者等Cydia上更新

那我等Cydia上更新吧，非常谢谢您的答覆
有了这个就可以去分析其他应用了层级对吗？

**Comment by creantan** [comment]
是的，如果还不行的话请提供下你手机型号

**Comment by League2EB** [comment]
> 是的，如果还不行的话请提供下你手机型号和系统版本

有预计1.0.4在Cydia什么时候上线吗？
好像要等BigBoss验证后才可以更新对吧

**Comment by creantan** [comment]
是的，需要验证

**Comment by League2EB** [comment]
> 是的，需要验证

验证过了也准备更新了，但我遇到了这个问题
<blockquote class="imgur-embed-pub" lang="en" data-id="a/7PCHRcM" data-context="false" ><a href="//imgur.com/a/7PCHRcM"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by creantan** [comment]
这个问题是theBigBoss源他自己重新打包造成的，你可以直接下载1.0.4版本：https://github.com/creantan/LookinLoader/releases
然后使用iFile手动安装

**Comment by League2EB** [comment]
> 这个问题是theBigBoss源他自己重新打包造成的，你可以直接下载1.0.4版本：https://github.com/creantan/LookinLoader/releases
> 然后使用iFile手动安装

好的，手动安装解决问题了，谢谢您
