### ISSUE TITLE
Installing Error.

### ISSUE THREAD

**Issue by marvss4** [creantan/LookinLoader#3]
iOS 12.1.1 7plus
i got an Installing Error

#
![8424C09B-C9B6-49C1-96FD-60BC5DDB3CF2](https://user-images.githubusercontent.com/53591777/62343035-b95af080-b51b-11e9-8cc2-264a86210b75.png)

**Comment by creantan** [comment]
> iOS 12.1.1 7plus
> i got an Installing Error
> 
> ![8424C09B-C9B6-49C1-96FD-60BC5DDB3CF2](https://user-images.githubusercontent.com/53591777/62343035-b95af080-b51b-11e9-8cc2-264a86210b75.png)

This error was caused by thebigboss repacking.
You can download the latest version here:https://github.com/creantan/LookinLoader/releases/download/1.0.4/com.chinapyg.lookinloader_1.0.4_iphoneos-arm.deb
and upload the deb file to your phone,then install it using iFile

**Comment by creantan** [comment]
You can update LookinLoader V1.0.4-1 from Cydia right now.
