### ISSUE TITLE
iOS 13.2.2 没有效果。

### ISSUE THREAD

**Issue by nlnlnull** [creantan/LookinLoader#5]
老哥，用新发布的 checkra1n 工具给 iPhone 6s iOS 13.2.2 越狱后，安装 lookinloader 没有效果，尚未发现任何 iOS App，晃动手机也没有弹出 UI 审查。

**Comment by nlnlnull** [comment]
刚刚发现打开 Cydia 有效果，其他的 App 还没有发现可以用的。

**Comment by creantan** [comment]
@nlnlnull 更新下版本：https://github.com/creantan/LookinLoader/releases/download/v1.0.6/com.chinapyg.lookinloader_1.0.6-1_iphoneos-arm.deb.zip

**Comment by 986138497** [comment]
老哥,cyida 商店还更新吗

**Comment by creantan** [comment]
@986138497 已更新到1.0.6版本了

**Comment by LeeCenY** [comment]
请问，是否可更新支持 iOS 14 呢
