### ISSUE TITLE
请问电脑版客户端更新了，如何将客户端本地的framework替换成与mac相对应的版本

### ISSUE THREAD

**Issue by trc19930224** [creantan/LookinLoader#6]

**Comment by creantan** [comment]
cydia里面搜索LookinLoader然后下载安装或者更新。
或者下载安装包自己安装：https://github.com/creantan/LookinLoader/releases/download/v1.0.5/com.chinapyg.lookinloader_1.0.5_iphoneos-arm.deb

**Comment by trc19930224** [comment]
好的，没问题了已经，多谢了
