### ISSUE TITLE
Hook into SpringBoard

### ISSUE THREAD

**Issue by DanielVolt** [creantan/LookinLoader#7]
Is there a way to attach into Springboard it self?

**Comment by creantan** [comment]
Yes, of course.Just inject LookinServer into Springboard and explore.

**Comment by DanielVolt** [comment]
thanks, looks amazing

https://github.com/DanielVolt/LookinLoader

**Comment by mac-user669** [comment]
> Just inject LookinServer into Springboard and explore.

I can't figure out how to do this, @DanielVolt could you help me? I built it from your fork, and made sure com.apple.springboard was in the plist along with com.apple.UIKit. What am I doing wrong?

**Comment by DanielVolt** [comment]
@mac-user669 are you sure LookinServer.framework is in (or even exists) /usr/lib/Lookin/LookinServer.framework/?

**Comment by mac-user669** [comment]
@DanielVolt Yes, it's there (I'm assuming you're talking about on the iOS device). Do you know if it works on iOS 13?

**Comment by DanielVolt** [comment]
@mac-user669 it works from iOS 13 -> 13.3. Have you shaken the device to bring up the UI?

**Comment by mac-user669** [comment]
T works when I enable apps in Settings, but it just doesn’t work on the SpringBoard

**Comment by DanielVolt** [comment]
Weird. what about USB? It also works with Lookin.app via USB on Mac

**Comment by mac-user669** [comment]
I have been using USB, and the official Lookin Mac app. When I have an app enabled in the Lookin settings pane (Settings for example), and I open that app, the Lookin Mac app will show it. Springboard doesn’t show in the tweak’s settings, so I can’t enable it, but com.apple.springboard is in /Library/MobileSubstrate/DynamicLibraries/LookinLoader.plist, along with com.apple.UIKit

**Comment by DanielVolt** [comment]
SpringBoard is NOT gonna show up in the settings... You have already loaded LookinFramework inside SpringBoard (Substrate has loaded it since i added it inside the plist), just shake the device to show up the Lookin UI and then export or do whatever u want. USB Support is partial and works very hacky

**Comment by mac-user669** [comment]
I figured it wouldn’t show in applist. I’ll try a few more things, thanks
