### ISSUE TITLE
iOS 13.5 iPhone 6s 1.0.6 连接电脑失效了。

### ISSUE THREAD

**Issue by nlnlnull** [creantan/LookinLoader#8]
作者你好，在手机端摇晃还是可以用，就是 macOS 上 的 lookin 加载不出来。

**Comment by L1cardo** [comment]
手机摇晃  电脑连接都不行

iPhone X  iOS13.5

**Comment by JamesWDGu** [comment]
手机摇晃 电脑连接都不行

iPhone xs max iOS13.5

**Comment by JamesWDGu** [comment]
> 手机摇晃 电脑连接都不行
> 
> iPhone xs max iOS13.5

只有 Cydia 可以。

**Comment by HOOKDLL** [comment]
回复楼上:目前手机摇晃可以使用的,前提要你要设置打开app, 由于macOS版本太低无法测试电脑连接!
ps:由于boss源没有同步github版本,造成boss源的摇一摇失效,目前已同步.

**Comment by JamesWDGu** [comment]
> 回复楼上:目前手机摇晃可以使用的,前提要你要设置打开app, 由于macOS版本太低无法测试电脑连接!
> ps:由于boss源没有同步github版本,造成boss源的摇一摇失效,目前已同步.

可以使用了，感谢
