### ISSUE TITLE
iPhone XR 手机 iOS13.5查看不了系统的app

### ISSUE THREAD

**Issue by caichunjian520** [creantan/LookinLoader#9]
第三方app可以查看，但是苹果自带的app例如计算器，时钟，App Store无论是连接mac用lookin或者是摇一摇都不能查看。已经在设置里的lookin中的Enabled Applications中打开了对应的app。

**Comment by HOOKDLL** [comment]
回复楼上:目前手机摇晃可以使用的,前提要你要设置打开app, 由于macOS版本太低无法测试电脑连接!
ps:由于boss源没有同步github版本,造成boss源的摇一摇失效,目前已同步.
我测试摇一摇系统app是没有问题的
